import { LevelDefinition } from '@/types';

export const ADDITION_LEVELS: LevelDefinition[] = [
  {
    level: 1,
    operation: 'addition',
    format: 'direct',
    questionCount: 36,
    timeLimit: { pass: 50, excellent: 35 },
    operands: { left: { min: 0, max: 9 }, right: { min: 0, max: 9 } },
    description: 'つぎの けいさんを しなさい。',
  },
  {
    level: 2,
    operation: 'addition',
    format: 'direct',
    questionCount: 36,
    timeLimit: { pass: 90, excellent: 60 },
    operands: { left: { min: 10, max: 99 }, right: { min: 1, max: 9 } },
    description: 'つぎの けいさんを しなさい。',
  },
  {
    level: 3,
    operation: 'addition',
    format: 'partial',
    questionCount: 36,
    timeLimit: { pass: 60, excellent: 40 },
    operands: { left: { min: 10, max: 99 }, right: { min: 10, max: 99 } },
    partialTarget: 'ones',
    description: 'つぎの けいさんの 1のくらいだけを たしなさい。',
  },
  {
    level: 4,
    operation: 'addition',
    format: 'partial',
    questionCount: 36,
    timeLimit: { pass: 80, excellent: 50 },
    operands: { left: { min: 10, max: 99 }, right: { min: 10, max: 99 } },
    partialTarget: 'tens',
    description: 'つぎの けいさんの 10のくらいだけを たしなさい。',
  },
  {
    level: 5,
    operation: 'addition',
    format: 'decomposed',
    questionCount: 18,
    timeLimit: { pass: 110, excellent: 70 },
    operands: { left: { min: 10, max: 99 }, right: { min: 10, max: 99 } },
    description: 'つぎの けいさんの 10のくらいだけを たして、1のくらいだけを たしてから こたえを もとめなさい。',
  },
  {
    level: 6,
    operation: 'addition',
    format: 'decomposed',
    questionCount: 18,
    timeLimit: { pass: 120, excellent: 80 },
    operands: { left: { min: 10, max: 99 }, right: { min: 10, max: 99 } },
    description: 'つぎの けいさんの 10のくらいだけを たして、1のくらいだけを たしてから こたえを もとめなさい。',
  },
  {
    level: 7,
    operation: 'addition',
    format: 'direct',
    questionCount: 36,
    timeLimit: { pass: 120, excellent: 80 },
    operands: { left: { min: 10, max: 99 }, right: { min: 10, max: 99 } },
    description: 'つぎの けいさんを しなさい。',
  },
  {
    level: 8,
    operation: 'addition',
    format: 'decomposed',
    questionCount: 18,
    timeLimit: { pass: 140, excellent: 90 },
    operands: { left: { min: 100, max: 999 }, right: { min: 10, max: 99 } },
    description: 'つぎの けいさんの 100のくらいと10のくらいだけを たして、1のくらいだけを たしてから こたえを もとめなさい。',
  },
  {
    level: 9,
    operation: 'addition',
    format: 'direct',
    questionCount: 36,
    timeLimit: { pass: 160, excellent: 110 },
    operands: { left: { min: 100, max: 999 }, right: { min: 10, max: 99 } },
    description: 'つぎの けいさんを しなさい。',
  },
  {
    level: 10,
    operation: 'addition',
    format: 'decomposed',
    questionCount: 18,
    timeLimit: { pass: 180, excellent: 120 },
    operands: { left: { min: 100, max: 999 }, right: { min: 100, max: 999 } },
    description: 'つぎの けいさんの 100のくらいと10のくらいだけを たして、1のくらいだけを たしてから こたえを もとめなさい。',
  },
  {
    level: 11,
    operation: 'addition',
    format: 'direct',
    questionCount: 36,
    timeLimit: { pass: 210, excellent: 140 },
    operands: { left: { min: 100, max: 999 }, right: { min: 100, max: 999 } },
    description: 'つぎの けいさんを しなさい。',
  },
];
